[package]
name = "commonplace-cli"
version = "0.0.0"
authors = ["Wesley Aptekar-Cassels <me@wesleyac.com>"]
edition = "2018"

[dependencies]
libcommonplace = { path = "../libcommonplace" }
structopt = "0.3.19"
uuid = { version = "0.8.1", features = [ "v4" ] }
walkdir = "2"
